### ISSUE TITLE
text lower bound to 1.2.3.*

### ISSUE THREAD

**Issue by ktonga** [poscat0x04/telegram-types#2]
text 1.2.4.0 does not build with ghc 8.10

**Comment by ktonga** [comment]
I also had to relax upper bounds for `lens` and `servant*` for it to resolve deps. But then it failed to compile `type-fun` with following error:

```
src/TypeFun/Data/List.hs:116:12: error:
    • Cannot instantiate unification variable ‘b1’
      with a type involving polytypes:
        proxy l -> ((l ~ (l :++: '[])) => r) -> r
        GHC doesn't yet support impredicative polymorphism
    • In the expression: unsafeCoerce id
      In an equation for ‘appendId’: appendId = unsafeCoerce id
    • Relevant bindings include
        appendId :: proxy l -> ((l ~ (l :++: '[])) => r) -> r
          (bound at src/TypeFun/Data/List.hs:116:1)
    |
116 | appendId = unsafeCoerce id
    |            ^^^^^^^^^^^^^^^

src/TypeFun/Data/List.hs:175:15: error:
    • Cannot instantiate unification variable ‘b0’
      with a type involving polytypes: (SubList l l => r) -> r
        GHC doesn't yet support impredicative polymorphism
    • In the expression: unsafeCoerce id
      In an equation for ‘subListId’: subListId _ = unsafeCoerce id
    • Relevant bindings include
        subListId :: proxy l -> (SubList l l => r) -> r
          (bound at src/TypeFun/Data/List.hs:175:1)
    |
175 | subListId _ = unsafeCoerce id
    |               ^^^^^^^^^^^^^^^
cabal: Failed to build type-fun-0.1.2 (which is required by
telegram-types-0.4.1). See the build log above for details.
```
